name: smarty_duelist
description: Turn-based tactical game.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Widgets, animations
  cupertino_icons: ^0.1.3
  flutter_platform_widgets: ^0.50.1
  flushbar: ^1.10.4
  animations: ^1.1.0
  flutter_form_builder: ^3.11.1
  # Bloc
  bloc: ^4.0.0
  flutter_bloc: ^4.0.1
  hydrated_bloc: ^4.1.1
  # Code generators and it dependencies
  meta: ^1.1.8
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  freezed_annotation: ^0.11.0
  json_serializable: ^3.3.0
  auto_route: ^0.5.0
  # Utils
  path_provider: ^1.6.10
  dartz: ^0.9.1
  rxdart: ^0.24.1
  # Firebase and dependencies
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.6
  # API
  google_sign_in: ^4.5.1
  image_picker: ^0.6.7+2
  extended_image: ^0.9.0
  image_editor: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  freezed: ^0.11.0
  build_runner: ^1.10.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.5.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en