name: smarty_duelist
description: Turn-based tactical game. My first personal commercial project :-)

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Widgets, animations
  cupertino_icons: ^0.1.3
  flutter_platform_widgets: ^0.32.5
  flushbar: ^1.9.1
  animations: ^1.0.0+5
  flutter_form_builder: ^3.8.2
  cached_network_image: ^2.1.0+1
  # Bloc
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  # Code generators and it dependencies
  meta: ^1.1.8
  get_it: ^4.0.1
  injectable: ^0.3.0
  freezed_annotation: ^0.7.1
  json_serializable: ^3.3.0
  auto_route: ^0.4.4
  # Utils
  path_provider: ^1.6.5
  dartz: ^0.8.9
  rxdart: ^0.23.1
  # Firebase and dependencies
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  # API
  google_sign_in: ^4.4.2
  image_picker: ^0.6.5
  extended_image: ^0.7.2
  image_editor: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  freezed: ^0.10.6
  build_runner: ^1.8.1
  injectable_generator: ^0.3.4
  auto_route_generator: ^0.4.5

dependency_overrides:
  intl: ^0.16.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en