name: 'Code check'

on:
  pull_request:

jobs:
  code_check:
    name: Code check
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v1
      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: flutter pub get
      - name: Generate code (freezed, auto_route, injectable, json_annotation)
        run: flutter pub run build_runner build
#      - name: run tests
#        run: flutter test
      - name: Run lint
        run: flutter analyze
      - name: Format code
        run: flutter format --set-exit-if-changed lib/src lib/main.dart
